/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'ws-poker-planning',
  DESCRIPTION: "Poker planning WebSocket server",
  VERSION: '1.2.1',
  VERSION_DATE: '2024-05-22',
});

export const LONG_VERSION_DATE = '1.2.1 (2024-05-22)';
